name: 01 - First Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
        working-directory: 01-demo-project
      - name: Print Goodbye
        run: echo "Done - Bye!"
        working-directory: 01-demo-project
