name: 06 - Events Demo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
        working-directory: 01-demo-project
      - name: Install dependencies
        run: npm ci
        working-directory: 01-demo-project
      - name: Test code
        run: npm run test
        working-directory: 01-demo-project
      - name: Build code
        run: npm run build
        working-directory: 01-demo-project
      - name: Deploy project
        run: echo "Deploying..."
        working-directory: 01-demo-project
